<<<<<<< HEAD
language: ruby
install:
 - unset DYLD_LIBRARY_PATH
 # Warning: You have a non-Homebrew 'pkg-config' in your PATH
 - sudo rm -f /usr/bin/pkg-config
 # Warning: "config" scripts exist outside your system or Homebrew directories.
 - sudo rm -f /usr/local/clang-3.4/bin/llvm-config
 # Incorrect file permissions: chmod 644
 - chmod 644 Library/Formula/*.rb
 - PATH=$PWD/bin:$PATH
script:
 - brew test-bot --dry-run $TRAVIS_COMMIT |sed -n 's/^==> //p' |sh -ex
notifications:
    email: false
